spring:
  application:
    name: premierProjet

  datasource:
    url: jdbc:postgresql://localhost:5432/ludotheque
    username: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
